// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGukHLeQZeiHW2OmOz7IJvCqwV_RkyqpE',
    appId: '1:400518549969:web:8935eccc54d864c38c90f0',
    messagingSenderId: '400518549969',
    projectId: 'socialify-213f8',
    authDomain: 'socialify-213f8.firebaseapp.com',
    storageBucket: 'socialify-213f8.appspot.com',
    measurementId: 'G-HDFV36VDNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAMvfKu1-RLxGjo2841UxsFK_qwPoXNE',
    appId: '1:400518549969:android:ccdd25e7a0fb1d058c90f0',
    messagingSenderId: '400518549969',
    projectId: 'socialify-213f8',
    storageBucket: 'socialify-213f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAjGk_MmGI-jOkJ-6n5hTP_Xjhi8aMig',
    appId: '1:400518549969:ios:ec69cfe573e5d1368c90f0',
    messagingSenderId: '400518549969',
    projectId: 'socialify-213f8',
    storageBucket: 'socialify-213f8.appspot.com',
    iosBundleId: 'com.example.socialify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAjGk_MmGI-jOkJ-6n5hTP_Xjhi8aMig',
    appId: '1:400518549969:ios:83987727efc354b48c90f0',
    messagingSenderId: '400518549969',
    projectId: 'socialify-213f8',
    storageBucket: 'socialify-213f8.appspot.com',
    iosBundleId: 'com.example.socialify.RunnerTests',
  );
}
